language: node_js
sudo: true
node_js:
- "4.1"
- "4.0"
- "0.12"
- "0.11"
- "0.10"
before_script: "npm install npm -g"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
