language: node_js
sudo: false
node_js:
	- "4.1"
	- "4.0"
	- "0.12"
	- "0.11"
	- "0.10"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
