version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: node -v
      - run: npm -v
      - run:
          name: Install dependencies
          command: npm ci
      - run: 
          name: Run unit tests
          command: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
      - codecov/upload:
        file: ./coverage/lcov.info
workflows:
  version: 2.1
  test:
    jobs:
      - test