version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: node -v
      - run: npm -v
      - run:
          name: Install dependencies
          command: npm ci
      - run: 
          name: Run unit tests
          command: npm test
      - run: 
          name: Generate code coverage
          command: cat ./coverage/**/lcov.info | ./node_modules/codecov/bin/codecov
      - store_artifacts:
          path: coverage
          prefix: coverage
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test